=== You don't want the Ink Spots to stutter, do you?

[NOTE]
====
Mods used in this chapter:

* http://www.nexusmods.com/fallout3/mods/19122[_UPDATED Unofficial Fallout 3 Patch_]
====

If you have a [line-through]#potato# old computer, like me, you may think that the Ink Spots had https://www.youtube.com/watch?v=6l6vqPUM_FE[a severe case of stuttering when it comes to singing]. It may be caused by some old sound libraries the game was bundled with.

Nevertheless, that is easy to fix (don't get used to that, though).

. Open the `[$FO3_HOME]` folder.
. Create a backup copy of the following two files:
* `libvorbis.dll`
* `libvorbisfile.dll`
. Download the [NexusFile]*VorbisUpdate* file from http://www.nexusmods.com/fallout3/mods/19122[_UPDATED Unofficial Fallout 3 Patch_].
. Unzip the file `VorbisUpdate-19122-1.zip` (or whatever its name is) in a location of your choice.
. Copy their namesakes from the unzipped file into `[$FO3_HOME]` folder.
. Copy the remaining DLL files into `[$FO3_HOME]`:
* `ogg.dll`
* `vorbis.dll`
* `vorbisenc.dll`

We are ready to begin with the serious shit. Stay tuned!
