== Introduction

I have always had, as far as my memory is able to recall, a strong bias for post-apocalyptic games, books and films. The tale of strong individuals or drawn-together communities struggling to survive in a harsh and unforgivable environment has always caught me. The _S.T.A.L.K.E.R._ series, by GSC Game World, the _Metro_ novels, by Dmitry Glukhovsky, or the _Prism Pentad_ novels in the _Dark Sun_ universe, by Troy Denning, are examples that come easily to mind.

I admit I never played the original _Fallout 1_ and _Fallout 2_ games, although they are considered to show https://warisboring.com/why-fallout-is-the-best-nuclear-war-story-ever-told/[the best depiction of the effects of a Nuclear War]. They went under my radar in my compulsive gaming-spree youth. But, oh my, when I first laid my eyes on _Fallout 3_, it was love at first sight. The game was released in 2008, and I have been playing it in and out since then, although I have never completed the main quest line. There are a lot of unfinished games in my backpack, I guess.

My first playthrough was with the Vanilla version of the game, and it was the longer one. And when I discovered mods, it taught me a valuable lesson: you should always play the unmodded version of the game, to get a sense of that could be improved or fixed.

I love post-apocalyptic games, and I love tinkering with things, so the recipe _Fallout 3_ + mods is a perfect win for me.

Slushes apart, _Fallout 3_ is an old game, and what it is more important, it is a Bethesda Softworks' game, and it means a lot of bugs out-of-the-box. The mods we are going to install address these bugs to fix the game, but they also greatly improve the game in every aspect, from playability to graphics, going through sounds and music.

So that is what we want to achieve with this guide: having a step-by-step process to get a fully modded _Fallout 3_ game, with no flaws (almost), with a serious performance boost and with visuals, audio and game mechanics enhanced, and all of this having a clean, pristine game data folder.

If you are in a rush of excitement and you cannot wait to start modding the hell out of _Fallout 3_, jump ahead to chapter <<DEFCON 00 (Vanilla)>>. Otherwise, read the rest of the introductory chapters to know <<Why Mod Organizer?, why are we choosing Mod Organizer as our modding tool>>, <<Functional vs. Technical, how is the guide organized and why>>, <<The tools we need, which are the tools we need to get the job done>>, and <<Conventions used in this guide, which are the conventions used in writing this guide>>.
