== The tools we need

These are the tools we are going to use throughout this guide. Don't worry about installing them yet; their setup will be addressed in the proper chapters. However, you can save precious time by downloading them right now.

Mod Organizer::
http://www.nexusmods.com/skyrim/mods/1334/[Mod Organizer] is an advanced modding tool. It is not as wide-scoped as Nexus Mod Manager, because it only supports _Fallout 3_, _Fallout New Vegas_, _The Elder Scrolls IV: Oblivion_ and _The Elder Scrolls V: Skyrim_ (not the _Special Edition_, though). However, is way more powerful than NMM. Once you start modding with it, you wonder where the fuck was this tool your whole life.

xEdit::
http://www.nexusmods.com/fallout4/mods/2737/[xEdit] comprises, in fact, several tools, each oriented to a specific game. Each version takes its name from the game it is aimed to, so the latest version is called FO4Edit, because it has been developed for _Fallout 4_. Nevertheless, each version works with any game in the _Fallout_ or _The Elder Scrolls_ series, from _Fallout 3_ and _Oblivion_ on. This tool allows us to fiddle with data files (`.esm` or `.esp`), cleaning them and modifying them if there is some kind of error. It also allows to clean data files, which have often duplicated or undeleted entries. Finally, it will help us to create a http://wiki.step-project.com/Guide:Merging_Plugins#xEdit_Merge_Patch[_Merged Patch_] to ensure a better game stability. More on that later on.

LOOT::
https://loot.github.io/[LOOT] is the best tool out there to keep your load order in check. It relies on an artifact called _the masterlist_, which is a list of mod's metadata to calculate the right load order for your mod stack.

Wrye Flash::
http://www.nexusmods.com/fallout3/mods/11336/[Wrye Flash] is a modding tool akin to Mod Organizer it is scope, but very different for what we are going to use it. It will help us to create a http://wiki.step-project.com/Bashed_Patch[_Bashed Patch_] to further improve our game stability.

Don't worry if the ultimate purpose of each tool seems a bit vague. All of this will be thoroughly explained in time.
